spring:
  application:
    name: mastermind

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/mastermind}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always # Sempre executa para testes locais

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:change-this-secret-key-with-at-least-32-characters}
  expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html